# Generated by Django 5.2.15 on 2026-06-13 09:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("language", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=255)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["starts_at"], name="events_even_starts__b01102_idx"),
                    models.Index(fields=["language"], name="events_even_languag_67ce95_idx"),
                    models.Index(fields=["location"], name="events_even_locatio_0ae1f4_idx"),
                    models.Index(
                        fields=["location", "starts_at"],
                        name="events_even_locatio_54abdf_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.search.SearchVector(
                            "title", "description", config="english"
                        ),
                        name="event_fts_gin",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="event_ends_after_starts",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("capacity__isnull", True),
                            ("capacity__gte", 1),
                            _connector="OR",
                        ),
                        name="event_capacity_positive",
                    ),
                ],
            },
        ),
    ]
